sass:
        sass_dir: _sass
incremental: true
grants:
  - id: '1550551'
  - id: '1550461'
  - id: '1550436'
  - id: '1550514'
    name: ''
  - id: '1212401'
  - id: '1212426'
  - id: '1212433'
  - id: '1212460'
    name: ''
  - id: '0903973'
  - id: '0903782'
  - id: '0904015'
    name: '(CIGR)'
  - id: '0701566'
  - id: '0855892'
    name: '(XiRel)'
  - id: '0721915'
    name: '(Alpaca)'
  - id: '0905046'
  - id: '0941653'
    name: '(PetaCactus/PRAC)'
